allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  prisma: set this to true or false
# Permite que os scripts de build do Prisma rodem no install (gera o Prisma Client)
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
